version: '3'
services:
  tally-bot:
    image: tally-bot:latest
    network_mode: "host"
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"