version: '3'
services:
  tally-bot:
    image: ryanpage/internal:tally-bot-dev
    network_mode: "host"
    restart: always
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"