name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: adminadmin
        ports:
          - 3307:3306

    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        sudo apt-get install -y nodejs make build-essential
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        export PATH=~/.npm-global/bin:$PATH
        npm i -g yarn
        npm i -g ts-mocha
        npm i -g mocha
        npm i -g typescript
        rm yarn.lock
        yarn install
    - name: Run tests
      run: |
        yarn test
